### ISSUE TITLE
Strange problem with row matrices

### ISSUE THREAD

**Issue by jcockayne** [wouterboomsma/eigency#11] opened 2017-03-20 21:14 UTC
Hi,
First I have been using eigency for a few months now and I absolutely love it! However, I see a repeated strange issue which occurs when I try to pass **row matrices** (that is, numpy arrays with a shape of `(1, N)`) from cython to c++ via Eigency.

When I pass a matrix of shape `(M, N)` the shape of the Eigen matrix is also `(M, N)` as it should be. But when I pass a matrix of shape `(1, N)` the Eigen matrix ends up transposed, having shape `(N, 1)`.

I'm aware of the common problem with non-fortran-order arrays appearing to be transposed once they reach C++, and as far as I can tell that's not what's happening here as it happens even if I create my arrays with `order='F'`

I've [attached](https://github.com/wouterboomsma/eigency/files/856389/Archive.zip) some reproducing code. On my machine I compiled this with the commands:

```
g++-6 -I /usr/local/include/eigen3 -c cpp_print_shape.cpp
python setup.py build_ext --inplace
```

Running `python test.py` then shows the problematic behaviour I've been seeing.

Please let me know if I'm doing something wrong here, or if this is a bug!

**Comment by wouterboomsma** [comment] 2017-03-20 22:08
Thanks for the report. I've just reproduced the problem on my machine. I'll try to find some time tomorrow to look into it.

**Comment by jcockayne** [comment] 2017-03-20 22:26
It looks like the problem may be that, if the array is 1D, it is reported as both C and F contiguous:
```
In [3]: tmp = np.array([[2, 2]], order='F')

In [4]: tmp.flags
Out[4]: 
  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  UPDATEIFCOPY : False
```
which looks like it messes with some of the logic in the map constructor. I'll see if I can fix it and submit a PR, if you don't object?

**Comment by wouterboomsma** [comment] 2017-03-20 22:29
Hehe...I didn't see your message until now - I just realized the exact same thing independently. I've already pushed a fix and a new release. Thanks so much for offering to help out - I would definitely have taken you up on it if I had noticed in time :)

**Comment by wouterboomsma** [comment] 2017-03-20 22:36
Just to follow up with a few more details. It had never occurred to me that an array could simultaneously obey both C and F layouts, but this is indeed the case for a (1,n) array. Since I checked for the presence of C layout (rather than the absence of F layout), this failed. I just switched from `PyArray_IS_C_CONTIGUOUS` to `!PyArray_IS_F_CONTIGUOUS` and now everything seems to work.

**Comment by jcockayne** [comment] 2017-03-20 22:37
Cool, that makes sense. Thanks very much for the super quick fix!

**Comment by wouterboomsma** [comment] 2017-03-20 22:44
No problem. Closing it now, but please reopen if there are still problems.

**Closed by wouterboomsma** 2017-03-20 22:44 UTC
